import assert from 'node:assert/strict';
import { once } from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { createFixtureServer } from '../bin/browser-debug/server.mjs';
import { assertBrowserEvidence } from '../bin/browser-debug/assert-evidence.mjs';

test('standalone loopback fixture supports form, login, HTTP and transport failures', async t => {
  const requests = [];
  const server = createFixtureServer(row => requests.push(row));
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
  const url = `http://127.0.0.1:${server.address().port}`;
  const page = await fetch(url).then(r => r.text());
  assert.match(page, /<label>Message/);
  assert.match(page, /sandbox-page-error-marker/);
  assert.deepEqual(await fetch(`${url}/api/session`).then(r => r.json()), { authenticated: false });
  assert.deepEqual(await fetch(`${url}/api/echo`, { method: 'POST', body: JSON.stringify({ message: 'example' }) }).then(r => r.json()), { message: 'example' });
  const denied = await fetch(`${url}/api/login`, { method: 'POST', body: '{"username":"other"}' });
  assert.equal(denied.status, 401);
  const login = await fetch(`${url}/api/login`, { method: 'POST', body: '{"username":"sandbox"}' });
  assert.equal(login.status, 200);
  assert.match(login.headers.get('set-cookie'), /HttpOnly/);
  assert.deepEqual(await fetch(`${url}/api/session`, { headers: { Cookie: 'ahsb-session=fixture-only' } }).then(r => r.json()), { authenticated: true });
  assert.equal((await fetch(`${url}/api/unavailable`)).status, 503);
  await assert.rejects(fetch(`${url}/api/drop`));
  assert.match(await fetch(`${url}/second`).then(r => r.text()), /Second page/);
  assert.ok(requests.some(row => row.dropped === true));
  assert.ok(requests.every(row => !('cookie' in row) && !('body' in row)));
});

test('evidence validator rejects missing behavior, disguised headless mode and invalid diagnostics', t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ahsb-browser-evidence-'));
  t.after(() => fs.rmSync(dir, { recursive: true }));
  const write = (name, data) => fs.writeFileSync(path.join(dir, name), typeof data === 'string' ? data : JSON.stringify(data));
  const dom = { message: 'VM-only browser input', session: 'Signed in', diagnostics: { status: 503, dropped: true } };
  write('agent-browser-version.txt', 'agent-browser 0.38.2');
  write('chromium-version.txt', 'Chromium fixture');
  write('mode.txt', 'headless');
  write('chrome-flags.txt', '--headless=new\n--remote-debugging-address=127.0.0.1');
  write('site.json', { url: 'http://127.0.0.1:1234' });
  write('dom.json', { success: true, data: { result: dom } });
  write('restored.json', { data: { result: { restored: true } } });
  write('tabs.json', { data: { tabs: [{ url: 'http://127.0.0.1:1234/' }, { url: 'http://127.0.0.1:1234/second' }] } });
  write('console.json', { data: ['sandbox-console-marker'] });
  write('errors.json', { data: ['sandbox-page-error-marker'] });
  write('network.json', { data: ['/api/unavailable'] });
  write('expected-timeout.json', { success: false, error: 'Timeout 1000ms exceeded while waiting for selector' });
  write('network.har', { log: { entries: [{ request: { url: 'http://127.0.0.1:1234/api/unavailable' }, response: { status: 503 } }] } });
  write('trace.json', { traceEvents: [{ name: 'event' }] });
  fs.writeFileSync(path.join(dir, 'browser.png'), Buffer.from('89504e470d0a1a0a', 'hex'));
  write('site-requests.jsonl', ['/api/echo', '/api/login', '/api/session', '/api/unavailable', '/api/drop', '/second'].map(route => JSON.stringify({ path: route })).join('\n'));
  assert.equal(assertBrowserEvidence(dir).stateRestored, true);
  write('dom.json', { data: { result: { ...dom, message: 'wrong input' } } });
  assert.throws(() => assertBrowserEvidence(dir), /DOM reflects/);
  write('dom.json', { data: { result: dom } });
  write('mode.txt', 'headed');
  assert.throws(() => assertBrowserEvidence(dir));
  write('mode.txt', 'headless');
  write('expected-timeout.json', { error: 'Unsupported flag --timeout' });
  assert.throws(() => assertBrowserEvidence(dir), /real timeout/);
  write('expected-timeout.json', { error: 'Timeout 1000ms exceeded' });
  write('trace.json', { traceEvents: [] });
  assert.throws(() => assertBrowserEvidence(dir), /trace contains events/);
});
